version: 2
jobs:
  build:
    docker:
      - image: circleci/node:boron-browsers
    branches:
      only:
        - master
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run lint
      - run: npm run build
      - deploy:
          command: npm run surge
